### ISSUE TITLE
Connecting to Raspberry GPIO

### ISSUE THREAD

**Issue by rafastryk** [pololu/drv8835-motor-driver-rpi#1]
Hi,

is it possible to use this library with the [DRV8835 Dual Motor Driver Carrier](https://www.pololu.com/product/2135)? Can you please describe how to connect Raspberry GPIO to the DRV8835?

**Comment by ryantm** [comment]
Hi, @toLLto.

It should be possible, if you duplicate the [schematic for the DRV8835 Dual
Motor Driver Kit for Raspberry Pi B+](https://www.pololu.com/file/0J805/drv8835-dual-motor-driver-kit-for-raspberry-pi-schematic.pdf). You will need a 20k resistor. If you need further help with this, please continue discussing it on the [Pololu Forum](http://forum.pololu.com), because this issue tracker is for problems with the library code.

Ryan
