### ISSUE TITLE
raspberry setup

### ISSUE THREAD

**Issue by vwasteels** [pololu/drv8835-motor-driver-rpi#3]
hello,

is there any raspberry setup prior to making this library work ?

I tried raspi-config and enabling serial shell, but no luck...

Thanks

**Comment by DavidEGrayson** [comment]
The instructions in the "Getting Started" section of the [README](https://github.com/pololu/drv8835-motor-driver-rpi) should be sufficient.  If you are unable to follow the instructions, I would need more details about what steps you have done and what is going wrong.

**Comment by vwasteels** [comment]
I followed each step, but can't get the motor working with example.py.

I just realized I was testing on a raspberry pi 2 B , I guess this is why... !

**Comment by DavidEGrayson** [comment]
When the README says "Pi 2", that includes the Raspberry Pi 2 Model B, so I don't think that's your problem.  Since your issue is unlikely to be a problem with the library's code, I'd recommend reading [this page](https://www.pololu.com/support) and then posting details about your setup and the issue you are experiencing on the Pololu forum.
